# Generated by Django 4.1 on 2022-08-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
